### ISSUE TITLE
Listing objects in dir

### ISSUE THREAD

**Issue by alikhajeh1** [rockuw/ram-policy-editor#1]
Sorry I can't speak Chinese but I have a question regarding the following that is mentioned in the README:
![screen shot 2016-12-05 at 12 15 35 am](https://cloud.githubusercontent.com/assets/638577/20870431/ff28173a-ba7f-11e6-8fa3-ea1b271a7680.png)

Is it not possible to have a policy that lets users list only items in a directory? For example, I have 1 bucket with folders:
user1-folder
user2-folder

And I want user1 to have full access to only user1-folder, so I've created a policy:
```
{
  "Version": "1",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "oss:*"
      ],
      "Resource": [
        "acs:oss:*:*:my-bucket/user1-folder/*"
      ]
    }
  ]
}
```

This lets user1 download/upload items in the bucket but not list, I cannot find a way to make list work. `aliyuncli oss List oss://my-bucket/user1-folder` returns AccessDenied 403.

P.S. I really like ram-policy-editor, AliCloud should link to it from their UI! Thanks!

**Comment by rockuw** [comment]
Sorry for inconvenience. 

In your case just check the "EnablePath" checkbox and you get what you want.

P.S. I will update README in English later.

**Comment by alikhajeh1** [comment]
Thanks, I tried the "EnablePath" option and it gave me the policy I pasted below. When I run:
- `aliyuncli oss List oss://my-bucket/user1-folder` 403 AccessDenied
- `aliyuncli oss ListAllObject oss://os-hgljg/user1-folder` 403 AccessDenied
- `aliyuncli oss ListAllDir oss://os-hgljg/user1-folder` works fine and lists the dirs only.

Uploading/downloading objects and creating folders inside user1-folder work fine, but I can't find a way to list objects. Is it not possible to list objects in a folder with policies?

```
{
  "Version": "1",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "oss:*"
      ],
      "Resource": [
        "acs:oss:*:*:my-bucket/user1-folder/*"
      ],
      "Condition": {}
    },
    {
      "Effect": "Allow",
      "Action": [
        "oss:ListObjects"
      ],
      "Resource": [
        "acs:oss:*:*:my-bucket"
      ],
      "Condition": {
        "StringLike": {
          "oss:Prefix": [
            "",
            "user1-folder/*"
          ]
        },
        "StringEquals": {
          "oss:Delimiter": "/"
        }
      }
    }
  ]
}
```

**Comment by alikhajeh1** [comment]
I found the answer (with help with AliCloud Support):
```
{
  "Version": "1",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "oss:*",
      "Resource": [
        "acs:oss:*:*:my-bucket/user1-folder/*"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "oss:ListObjects"
      ],
      "Resource": [
        "acs:oss:*:*:my-bucket"
      ],
      "Condition": {
        "StringLike": {
          "oss:Prefix": "user1-folder/*"
        }
      }
    }
  ]
}
```

So it seems like the following part of the policy that was generated by the EnablePath option was blocking the ability to list objects
```
        "StringEquals": {
          "oss:Delimiter": "/"
        }
```
